[package]
name = "ehrenfest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0.34"
ndarray = "0.16.1"
num = "0.4.3"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"